package aichat

import (
	"testing"
	"time"
)

// TestChatPromptsByteExact pins the French chat prompts to the exact bytes produced by the
// TypeScript template literals in src/application/ai-chat-assistant.ts:225-237. The expected
// strings were generated by evaluating those literals with node against the same mockDocs()
// fixture; the model's behaviour depends on every byte, including the accented characters, the em
// dash and the warning emoji with its U+FE0F variation selector.
func TestChatPromptsByteExact(t *testing.T) {
	now := time.Date(2026, 8, 12, 0, 0, 0, 0, time.Local)

	system, user := BuildPromptContext("Show my pay slip", mockDocs(), now)
	if system != wantChatSystem {
		t.Fatalf("chat system mismatch:\n got %q\nwant %q", system, wantChatSystem)
	}
	if user != wantChatUser {
		t.Fatalf("chat user mismatch:\n got %q\nwant %q", user, wantChatUser)
	}

	_, relative := BuildPromptContext("3 derniers mois", mockDocs(), now)
	if relative != wantChatUserRelative {
		t.Fatalf("chat user (relative) mismatch:\n got %q\nwant %q", relative, wantChatUserRelative)
	}
}

const wantChatSystem = `Tu es un assistant archiviste IA local expert pour le tri et la préparation de dossiers administratifs (via outils MCP locaux).
Ta mission est de répondre à la demande de l'utilisateur de manière synthétique et professionnelle en français.

Nous sommes le 2026-08-12. Utilise cette date comme "aujourd'hui" pour toute expression temporelle relative dans la demande de l'utilisateur (ex: "les 3 derniers mois", "cette année", "le mois dernier") — calcule la période exacte à partir de cette date avant de comparer aux dates des documents fournis.

Consignes strictes:
1. Analyse les documents fournis ci-dessous (triés par pertinence et par date via les outils MCP).
2. Sélectionne et liste EXACTEMENT les documents nécessaires qui répondent à la demande.
3. Pour CHAQUE document listé ci-dessous qui fait partie de ta réponse, mentionne obligatoirement son identifiant sous la forme [Doc #ID: Titre] (exemple: [Doc #1810: Bulletin de Salaire - Décembre 2024]) — n'omets aucune citation, un document non cité sera considéré comme non inclus dans la réponse.
4. Si des pièces obligatoires pour le dossier sont absentes de l'archive, indique-les sous "⚠️ Documents manquants suggérés".
5. Réponds directement en texte clair Markdown sans balises JSON raw.`

const wantChatUser = `Documents disponibles dans la base locale (via MCP):
[Doc #1] Title: "Facture EDF Electricite" | Format: PDF | Category: housing/edf | Date: 2024-01-15 | Amount: 85.50
Summary: Invoice for electricity

[Doc #2] Title: "Bulletin de Salaire Mai 2026" | Format: PDF | Category: bulletin_salaire/acme_corp | Date: 2026-05-31 | Amount: 2450.00
Summary: Monthly pay slip AcmeCorp

[Doc #3] Title: "Bulletin de Salaire Juin 2026" | Format: PDF | Category: bulletin_salaire/acme_corp | Date: 2026-06-30 | Amount: 2450.00
Summary: June pay slip AcmeCorp

Demande de l'utilisateur: "Show my pay slip"`

const wantChatUserRelative = `Documents disponibles dans la base locale (via MCP):
[Doc #1] Title: "Facture EDF Electricite" | Format: PDF | Category: housing/edf | Date: 2024-01-15 | Amount: 85.50
Summary: Invoice for electricity

[Doc #2] Title: "Bulletin de Salaire Mai 2026" | Format: PDF | Category: bulletin_salaire/acme_corp | Date: 2026-05-31 | Amount: 2450.00
Summary: Monthly pay slip AcmeCorp

[Doc #3] Title: "Bulletin de Salaire Juin 2026" | Format: PDF | Category: bulletin_salaire/acme_corp | Date: 2026-06-30 | Amount: 2450.00
Summary: June pay slip AcmeCorp

Demande de l'utilisateur: "3 derniers mois"`
