// Package prompt is a Go port of pdf-triage's src/domain/prompt.ts (174 lines), which builds the
// three Qwen prompts used by the triage pipeline: Step A entity extraction
// (buildEntityExtractionPrompt), Step C chunk-by-chunk Markdown conversion
// (buildMarkdownConversionPrompt) and Step D classification (buildClassificationPrompt), plus the
// ILLEGIBLE_FRAGMENT_MARKER constant and the MarkdownContinuationContext shape. The ported upstream
// suites are src/domain/prompt.test.ts (15 cases) and src/domain/prompt-injection.test.ts (4 cases).
//
// The TypeScript source is the behavioral source of truth. The prompt bytes matter because Qwen's
// behavior depends on them, so the package additionally pins byte-exact fixtures generated by the
// real TS implementation (prompt/testdata/) and a guard that every {{PLACEHOLDER}} declared by the
// committed prompts/ templates is substituted in every built prompt. src/domain/prompt-hygiene.test.ts
// is deliberately NOT ported: it scans the whole repo tree against the operator's
// CONFIG.PERSONAL_NAME_DENYLIST, which lives in the gitignored settings.json, and is red upstream
// against that denylist; a Go equivalent does not belong in a domain package (see the package
// README note in the job report), but a repo-wide hygiene scan at cutover would be reasonable as a
// separate CI job, not a unit test.
//
// Dependency injection (the package performs no I/O of its own). The TS module reaches into two
// infrastructure places:
//
//   - It reads template files with fs from CONFIG.PROMPTS_DIR (loadPromptPart). Here Deps.Templates
//     is an injected fs.FS; a missing file (or a nil FS) selects the hardcoded TS fallback exactly
//     as `fs.existsSync` returning false does. Production composition supplies os.DirFS(CONFIG.
//     PROMPTS_DIR); tests supply fstest.MapFS / t.TempDir / os.DirFS(real prompts).
//   - It calls getPromptPersonalization() (prompt-personalization-store.ts) on every build, which
//     itself reads .prompts.private.json and appends learned priority rules and taxonomy-conflict
//     hints. Here Deps.Personalization is an injected `func() promptpersonalization.
//     PromptPersonalization`; nil means EMPTY_PROMPT_PERSONALIZATION. The later store port supplies
//     the real reader. The pure rendering (RenderPriorityRulesBlock / RenderKnownEntitiesBlock)
//     reuses the sibling promptpersonalization package rather than reimplementing it.
//
// It also reuses classification.PreprocessRawText and classification.FormatLocalDate instead of
// re-porting them.
//
// Deviations, all resolved in favor of matching TS exactly:
//
//  1. JS whitespace. loadPromptPart's `.trim()` uses JavaScript's WhiteSpace+LineTerminator set
//     (NBSP U+00A0, the Unicode space separators, U+2028/U+2029, the BOM U+FEFF, …). Go's
//     strings.TrimSpace follows unicode.White_Space and would disagree, so jsTrim reproduces
//     String.prototype.trim() exactly. It and the isJSWhitespace set mirror the unexported
//     classification helpers (the domain packages are not modified and these are not exported).
//  2. UTF-16 length and substring. JS `str.length` counts UTF-16 code units and
//     `cleanRawText.substring(0, 2000/4000)` cuts on a code unit; utf16Len / utf16Slice reproduce
//     both. The corpus is BMP, where a code unit is a rune; for astral text utf16Slice drops a rune
//     whose code units straddle the cut, whereas JS would keep a lone surrogate — unrepresentable
//     in a Go UTF-8 string. TextSnippetLength is a UTF-16 length, not a byte length.
//  3. JavaScript string-replacement substitution. A string search/replacement in JS expands `$$`,
//     `$&`, the before-match dollar-backtick form and `$'` in the replacement (GetSubstitution).
//     jsReplaceFirst / jsReplaceAll reproduce that; Go's strings.Replace is purely literal and
//     would diverge when a filename, text snippet or rendered overlay block contains `$`.
//  4. Optional parameters. TS's optional `continuationContext` / `repairNote` / `previousError` /
//     `systemLanguage` / `entityHint` / `now` become explicit parameters plus a ClassificationOptions
//     struct with TS defaults (systemLanguage "" -> FR, zero Now -> time.Now()). A *EntityHint nil
//     is TS undefined; an empty Entity string disables the block, matching JS truthiness.
//  5. The `console.warn` in loadPromptPart's catch is a logging side effect, not a result; this
//     pure domain package does not emit it. The observable prompt is identical.
//  6. `getPromptPersonalization()` is called fresh on every TS build; the injected
//     Deps.Personalization function is likewise invoked per build, so a changing overlay is seen.
package prompt

import (
	"io/fs"
	"strings"
	"time"

	"github.com/phamhung075/pdf-triage-pdf2w/classification"
	"github.com/phamhung075/pdf-triage-pdf2w/promptpersonalization"
)

// IllegibleFragmentMarker ports the exported TS constant of the same name. It is emitted by the
// model (per prompt rule 5) when a raw-text fragment is illegible / doesn't resolve into coherent
// words in any language, instead of being fabricated.
const IllegibleFragmentMarker = "⚠️ [Illegible fragment — preserved as-is]"

const entityExtractionSystem = "You are a specialized document entity extraction agent. Respond ONLY in valid JSON."
const markdownConversionSystem = "You are a high-precision document to Markdown converter. Output ONLY valid Markdown with zero skipping."

// Prompt mirrors the TS `{ system: string; user: string }` return of
// buildEntityExtractionPrompt / buildMarkdownConversionPrompt.
type Prompt struct {
	System string
	User   string
}

// ClassificationPrompt mirrors the TS buildClassificationPrompt return, including the UTF-16
// textSnippetLength.
type ClassificationPrompt struct {
	System            string
	User              string
	TextSnippetLength int
}

// MarkdownContinuationContext ports the TS interface of the same name: when the previous chunk's
// converted Markdown ended mid-table, its detected header + separator row are passed here so the
// next chunk continues the same table instead of re-opening one.
type MarkdownContinuationContext struct {
	Header    string
	Separator string
}

// EntityHint ports the TS structural `{ entity: string; docType?: string }` argument.
type EntityHint struct {
	Entity  string
	DocType string
}

// ClassificationOptions carries the optional buildClassificationPrompt arguments. The zero value
// applies the TS defaults (FR language, now = time.Now(), no error, no hint).
type ClassificationOptions struct {
	PreviousError  string
	SystemLanguage string
	EntityHint     *EntityHint
	Now            time.Time
}

// Deps is the explicit injected surface. See the package comment.
type Deps struct {
	// Templates is the prompt-template filesystem (TS CONFIG.PROMPTS_DIR). nil or a missing file
	// selects the TS hardcoded fallback.
	Templates fs.FS
	// Personalization returns the private prompt overlay (TS getPromptPersonalization). nil is
	// EMPTY_PROMPT_PERSONALIZATION.
	Personalization func() promptpersonalization.PromptPersonalization
}

func (d Deps) personalization() promptpersonalization.PromptPersonalization {
	if d.Personalization != nil {
		return d.Personalization()
	}
	return promptpersonalization.EMPTY_PROMPT_PERSONALIZATION
}

// loadPromptPart ports loadPromptPart: the trim()'d file content, or the trim()'d fallback when the
// file cannot be read (TS `fs.existsSync` false or a read error).
func (d Deps) loadPromptPart(filename, fallbackDefault string) string {
	if d.Templates != nil {
		if data, err := fs.ReadFile(d.Templates, filename); err == nil {
			return jsTrim(string(data))
		}
	}
	return jsTrim(fallbackDefault)
}

// BuildEntityExtractionPrompt ports buildEntityExtractionPrompt (Step A).
func (d Deps) BuildEntityExtractionPrompt(filename, rawText string) Prompt {
	cleanRawText := classification.PreprocessRawText(rawText)
	textSnippet := cleanRawText
	if utf16Len(cleanRawText) > 2000 {
		textSnippet = utf16Slice(cleanRawText, 2000)
	}

	template := d.loadPromptPart("micro_prompt_entity.md", entityExtractionFallback)
	user := jsReplaceAll(template, "{{USER_KNOWN_ENTITIES}}", promptpersonalization.RenderKnownEntitiesBlock(d.personalization()))
	user = jsReplaceFirst(user, "{{FILENAME}}", filename)
	user = jsReplaceFirst(user, "{{TEXT_SNIPPET}}", textSnippet)
	return Prompt{System: entityExtractionSystem, User: user}
}

// BuildMarkdownConversionPrompt ports buildMarkdownConversionPrompt (Step C).
func (d Deps) BuildMarkdownConversionPrompt(chunkText string, continuationContext *MarkdownContinuationContext, repairNote string) Prompt {
	template := d.loadPromptPart("micro_prompt_markdown.md", markdownConversionFallback)

	continuationBlock := ""
	if continuationContext != nil && continuationContext.Header != "" {
		continuationBlock = "\n⚠️ CONTINUATION CONTEXT: The previous chunk ended mid-table with this open table (header row: \"" +
			continuationContext.Header + "\"; column separator: \"" + continuationContext.Separator +
			"\"). If this chunk continues the same tabular data, output ONLY the continuing `| cell | cell |` rows — do NOT repeat the header/separator row and do NOT start a new table for the same data. If this chunk does not continue that table, ignore this note.\n"
	}
	repairBlock := ""
	if repairNote != "" {
		repairBlock = "\n⚠️ REPAIR REQUEST (this is a RE-CONVERSION of the same chunk): " + repairNote +
			"\nConvert the SAME raw text chunk below again, correcting only the listed problems. Keep 100% of the content. Output ONLY the corrected Markdown.\n"
	}

	user := jsReplaceFirst(template, "{{CONTINUATION_CONTEXT}}", continuationBlock+repairBlock)
	user = jsReplaceFirst(user, "{{CHUNK_TEXT}}", chunkText)
	return Prompt{System: markdownConversionSystem, User: user}
}

// BuildClassificationPrompt ports buildClassificationPrompt (Step D).
func (d Deps) BuildClassificationPrompt(categoriesDescriptionStr, filename, rawText string, opts ClassificationOptions) ClassificationPrompt {
	cleanRawText := classification.PreprocessRawText(rawText)
	textSnippet := cleanRawText
	if utf16Len(cleanRawText) > 4000 {
		textSnippet = utf16Slice(cleanRawText, 4000) + "..."
	}

	systemLanguage := opts.SystemLanguage
	if systemLanguage == "" {
		systemLanguage = "FR"
	}
	now := opts.Now
	if now.IsZero() {
		now = time.Now()
	}

	// markdown_content is no longer requested from this step — Step C (convertRawTextToZeroLossMarkdown)
	// already produces it chunk-by-chunk before this call runs, and Step D regenerating its own copy
	// was pure wasted num_predict budget that was thrown away >50% of the time anyway (see
	// classify-document.ts's former length-comparison guard, now removed).
	langInstruction := "IMPORTANT: Générez le \"titre\" et le \"summary\" en français."
	if systemLanguage == "EN" {
		langInstruction = "IMPORTANT: Generate the output \"titre\" and \"summary\" in English."
	}

	systemHeader := d.loadPromptPart("system_header.md", "")
	systemHeader = jsReplaceFirst(systemHeader, "{{LANG_INSTRUCTION}}", langInstruction)
	systemHeader = jsReplaceFirst(systemHeader, "{{CATEGORIES_DESCRIPTION}}", categoriesDescriptionStr)

	contactRules := d.loadPromptPart("contact_rules.md", "")

	// classification_rules.md is committed and generic; the personal keyword overrides that used
	// to be hardcoded into its STEP 1/2/5/6/7/10 keyword lists now come from the gitignored
	// .prompts.private.json overlay and are injected as a STEP 0, ahead of the generic flow (a
	// strict-order decision flow means an appended-at-the-end block would never fire for the
	// document types these overrides exist to catch).
	classificationRules := d.loadPromptPart("classification_rules.md", "")
	classificationRules = jsReplaceAll(classificationRules, "{{USER_PRIORITY_RULES}}", promptpersonalization.RenderPriorityRulesBlock(d.personalization()))

	formattingRules := d.loadPromptPart("formatting_rules.md", "")
	formattingRules = jsReplaceAll(formattingRules, "{{CURRENT_DATE}}", classification.FormatLocalDate(now))

	jsonSchema := d.loadPromptPart("json_schema_response.json", "")

	systemTemplate := d.loadPromptPart("system_template.md", systemTemplateFallback)
	system := systemTemplate
	system = jsReplaceFirst(system, "{{SYSTEM_HEADER}}", systemHeader)
	system = jsReplaceFirst(system, "{{CONTACT_RULES}}", contactRules)
	system = jsReplaceFirst(system, "{{CLASSIFICATION_RULES}}", classificationRules)
	system = jsReplaceFirst(system, "{{FORMATTING_RULES}}", formattingRules)
	system = jsReplaceFirst(system, "{{JSON_SCHEMA}}", jsonSchema)

	retryFeedback := ""
	if opts.PreviousError != "" {
		retryTemplate := d.loadPromptPart("retry_prompt.md", retryPromptFallback)
		retryFeedback = jsReplaceFirst(retryTemplate, "{{PREVIOUS_ERROR}}", opts.PreviousError)
	}

	// Step A (BuildEntityExtractionPrompt) already ran a dedicated, focused extraction pass over
	// this exact document and identified its issuing entity with higher reliability than asking
	// this single freeform call to both re-derive the entity AND pick the right category in one
	// shot. Without an explicit instruction the model tends to re-analyze from scratch and can
	// still land on a generic fallback category (e.g. 'correspondence') even when hint is correct
	// (this was the root cause of the Crédit Mutuel bank-statement regression — Step A correctly
	// identified the full branch name but Step D still said 'correspondence').
	entityHintBlock := ""
	if opts.EntityHint != nil && opts.EntityHint.Entity != "" {
		entityHintBlock = "\n\n⚠️ PRE-EXTRACTED ENTITY HINT (TREAT AS GROUND TRUTH UNLESS DIRECTLY CONTRADICTED BY THE DOCUMENT TEXT BELOW):\nA dedicated entity-extraction pass already analyzed this exact document and identified the issuing entity as \"" +
			opts.EntityHint.Entity + "\""
		if opts.EntityHint.DocType != "" {
			entityHintBlock += " (document type: \"" + opts.EntityHint.DocType + "\")"
		}
		entityHintBlock += ". Use this identification to choose BOTH the top-level Category and the Subcategory — e.g. if the entity is a bank, Category MUST be 'bank', not a generic fallback like 'correspondence'. Only ignore this hint if the Document Text Content below clearly proves it wrong."
	}

	userTemplate := d.loadPromptPart("user_template.md", userTemplateFallback)
	user := userTemplate
	user = jsReplaceFirst(user, "{{FILENAME}}", filename)
	user = jsReplaceFirst(user, "{{TEXT_SNIPPET}}", textSnippet)
	user = jsReplaceFirst(user, "{{RETRY_FEEDBACK}}", retryFeedback+entityHintBlock)

	return ClassificationPrompt{System: system, User: user, TextSnippetLength: utf16Len(textSnippet)}
}

// ---- Hardcoded fallbacks (byte-exact transcriptions of the TS template literals) ----

const entityExtractionFallback = `Analyze the following raw document text and filename.
Your ONLY task is to identify:
1. "issuing_entity": The official issuing company, bank, employer, school, hospital, or government organization issuing this document.
   - Ignore employee names, personal customer names, or internal transaction rows!
2. "document_type": The specific type of document (e.g. "Pay Slip", "Bank Statement", "Tax Assessment", "Invoice", "Work Contract", "Identity Document").
{{USER_KNOWN_ENTITIES}}
Filename: {{FILENAME}}

Document Text Snippet:
{{TEXT_SNIPPET}}

Respond ONLY with raw JSON:
{"issuing_entity": "...", "document_type": "..."}`

const markdownConversionFallback = `Convert the following raw text chunk into clean, structured GitHub Flavored Markdown (GFM).
STRICT RULES:
1. ZERO CONTENT SKIPPING: Convert 100% of the raw text accurately into Markdown. Do NOT skip, omit, or summarize any words, numbers, amounts, or table rows.
2. TABLES ARE FOR REPEATED ROWS ONLY: Use a GFM Markdown table only for genuinely tabular data with multiple rows sharing the same columns. Do NOT force a one-row table to hold several unrelated fields — list those as separate **Label:** Value lines instead.
3. STRUCTURAL HEADINGS: Use #, ##, ### for headings, and **bold** for key-value labels. This chunk may be a fragment with no visibility into prior chunks (except for any CONTINUATION CONTEXT note below, if present) — keep headings shallow.
4. NO CONVERSATIONAL COMMENTARY: Output ONLY the converted Markdown text.
5. NEVER FABRICATE FROM PATTERN-RECOGNITION: If a fragment of the raw text is illegible or does not resolve into coherent words in ANY language (OCR noise, garbled encoding, random letter fragments), do NOT invent plausible-looking content and do NOT translate or interpret characters you cannot actually make out — even when the fragment's shape pattern-matches a well-known document type you recognize from training (e.g. a Vietnamese balance sheet, a French payslip). Recognizing the document TYPE is not license to fabricate that document type's usual field values. Instead, preserve the illegible fragment near-verbatim, or mark it clearly with a blockquote:
> ` + IllegibleFragmentMarker + `
followed by the raw fragment text.
{{CONTINUATION_CONTEXT}}
Raw Text Chunk:
{{CHUNK_TEXT}}`

const systemTemplateFallback = `{{SYSTEM_HEADER}}

{{CONTACT_RULES}}

{{CLASSIFICATION_RULES}}

{{FORMATTING_RULES}}

Respond ONLY with raw JSON matching this structure:
{{JSON_SCHEMA}}`

const retryPromptFallback = "\n\n" + `⚠️ PREVIOUS ATTEMPT FEEDBACK (FIX THIS PROBLEM):
The previous classification attempt for this document encountered an error: "{{PREVIOUS_ERROR}}".
Please carefully analyze the document text and fix this issue. You MUST provide a specific, valid Category and Subcategory slug that is genuinely grounded in the Document Text Content (e.g. 'credit_mutuel', 'impot', 'ameli', 'sfr') — do NOT derive it from the filename. If no real entity is identifiable in the text, it is correct to return 'general' rather than guessing.`

const userTemplateFallback = `Filename: {{FILENAME}}

Document Text Content:
{{TEXT_SNIPPET}}{{RETRY_FEEDBACK}}`

// ---- JS string semantics helpers ----

// jsReplaceFirst ports `str.replace(search, replacement)` for a string `search`: the first
// occurrence only, with GetSubstitution expansion of the replacement.
func jsReplaceFirst(s, search, replacement string) string {
	i := strings.Index(s, search)
	if i < 0 {
		return s
	}
	return s[:i] + expandJSReplacement(s, replacement, i, search) + s[i+len(search):]
}

// jsReplaceAll ports a global `str.replace(/literal/g, replacement)`: every non-overlapping
// occurrence, with GetSubstitution expansion computed against the original input.
func jsReplaceAll(s, search, replacement string) string {
	if search == "" {
		return s
	}
	var b strings.Builder
	pos := 0
	for {
		i := strings.Index(s[pos:], search)
		if i < 0 {
			break
		}
		start := pos + i
		b.WriteString(s[pos:start])
		b.WriteString(expandJSReplacement(s, replacement, start, search))
		pos = start + len(search)
	}
	b.WriteString(s[pos:])
	return b.String()
}

// expandJSReplacement ports the GetSubstitution replacement patterns that apply to a string
// search (no capture groups): `$$`, `$&`, the before-match dollar-backtick form and `$'`. Any
// other `$x` is left literal, as JS does when the pattern names no capture group.
func expandJSReplacement(s, replacement string, matchStart int, matched string) string {
	var b strings.Builder
	for i := 0; i < len(replacement); i++ {
		c := replacement[i]
		if c != '$' || i+1 >= len(replacement) {
			b.WriteByte(c)
			continue
		}
		switch replacement[i+1] {
		case '$':
			b.WriteByte('$')
			i++
		case '&':
			b.WriteString(matched)
			i++
		case '`':
			b.WriteString(s[:matchStart])
			i++
		case '\'':
			b.WriteString(s[matchStart+len(matched):])
			i++
		default:
			b.WriteByte('$')
		}
	}
	return b.String()
}

// jsTrim is `String.prototype.trim()`: it strips exactly the JavaScript whitespace set. Go's
// strings.TrimSpace would additionally strip U+0085 NEL and would leave U+FEFF.
func jsTrim(s string) string {
	return strings.TrimFunc(s, isJSWhitespace)
}

// isJSWhitespace reports whether r is in JavaScript's WhiteSpace+LineTerminator set.
func isJSWhitespace(r rune) bool {
	switch r {
	case '\t', '\n', '\v', '\f', '\r', ' ',
		0x00A0, 0x1680, 0x2028, 0x2029, 0x202F, 0x205F, 0x3000, 0xFEFF:
		return true
	}
	return r >= 0x2000 && r <= 0x200A
}

// utf16Len is JavaScript's `str.length`: the number of UTF-16 code units, not runes.
func utf16Len(s string) int {
	n := 0
	for _, r := range s {
		if r > 0xFFFF {
			n += 2
		} else {
			n++
		}
	}
	return n
}

// utf16Slice reproduces `str.substring(0, n)`: the first n UTF-16 code units. A rune whose code
// units would straddle the cut is dropped; JS would keep a lone surrogate there, which a Go UTF-8
// string cannot represent.
func utf16Slice(s string, n int) string {
	if n <= 0 {
		return ""
	}
	units := 0
	for i, r := range s {
		w := 1
		if r > 0xFFFF {
			w = 2
		}
		if units+w > n {
			return s[:i]
		}
		units += w
	}
	return s
}
