package chatplanner

import (
	"testing"
	"time"
)

// TestPlannerPromptByteExact pins the French planner prompt to the exact bytes produced by the
// TypeScript template literal in src/application/chat-query-planner.ts:22-49. The two expected
// strings were generated by evaluating that literal with node; the model's behaviour depends on
// every byte, including the accented characters and the em dash.
func TestPlannerPromptByteExact(t *testing.T) {
	now := time.Date(2026, 8, 26, 0, 0, 0, 0, time.Local)

	system, user := BuildPlannerPrompt("rib", []string{"bank", "identity"}, now)
	if system != wantPlannerSystemTwoCategories {
		t.Fatalf("planner system mismatch:\n got %q\nwant %q", system, wantPlannerSystemTwoCategories)
	}
	if user != `Demande: "rib"` {
		t.Fatalf("planner user mismatch: %q", user)
	}

	systemSingle, _ := BuildPlannerPrompt("rib", []string{"bank"}, now)
	if systemSingle != wantPlannerSystemOneCategory {
		t.Fatalf("planner system (single category) mismatch:\n got %q\nwant %q", systemSingle, wantPlannerSystemOneCategory)
	}
}

const wantPlannerSystemTwoCategories = `Tu convertis une demande de document en requête de recherche structurée JSON.
Tu ne réponds JAMAIS à la demande — tu produis UNIQUEMENT l'objet JSON.

Nous sommes le 2026-08-26. Résous toute expression temporelle relative
("les 3 derniers mois", "cette année", "l'an dernier") en dates ISO à partir de cette date.

Catégories disponibles: bank, identity.

Renvoie exactement cet objet:
{
  "docTypes": [],   // le TYPE de document demandé, avec ses synonymes usuels et son sigle.
                    // Ex: pour un RIB -> ["rib", "relevé d'identité bancaire", "iban", "bic"]
  "entities":  [],  // l'organisme / l'émetteur cité, avec ses variantes et abréviations
  "keywords":  [],  // les autres termes porteurs de sens (jamais de mots vides)
  "notTerms":  [],  // les types de documents à EXCLURE quand ils se confondent avec la demande.
                    // Ex: pour un RIB -> ["relevé de compte", "mouvement"]
  "category":  null,        // une des catégories ci-dessus, ou null
  "subcategory": null,
  "dateFrom":  null,        // "YYYY-MM-DD" ou null
  "dateTo":    null,
  "limit":     null         // nombre de documents demandé, ou null
}

Règles:
- Mets des SYNONYMES dans docTypes: c'est ce qui rattrape un document mal titré.
- notTerms est ce qui sépare deux documents du même organisme. Utilise-le.
- N'invente pas de catégorie absente de la liste. Dans le doute, null.
- Aucun texte hors du JSON.`

const wantPlannerSystemOneCategory = `Tu convertis une demande de document en requête de recherche structurée JSON.
Tu ne réponds JAMAIS à la demande — tu produis UNIQUEMENT l'objet JSON.

Nous sommes le 2026-08-26. Résous toute expression temporelle relative
("les 3 derniers mois", "cette année", "l'an dernier") en dates ISO à partir de cette date.

Catégories disponibles: bank.

Renvoie exactement cet objet:
{
  "docTypes": [],   // le TYPE de document demandé, avec ses synonymes usuels et son sigle.
                    // Ex: pour un RIB -> ["rib", "relevé d'identité bancaire", "iban", "bic"]
  "entities":  [],  // l'organisme / l'émetteur cité, avec ses variantes et abréviations
  "keywords":  [],  // les autres termes porteurs de sens (jamais de mots vides)
  "notTerms":  [],  // les types de documents à EXCLURE quand ils se confondent avec la demande.
                    // Ex: pour un RIB -> ["relevé de compte", "mouvement"]
  "category":  null,        // une des catégories ci-dessus, ou null
  "subcategory": null,
  "dateFrom":  null,        // "YYYY-MM-DD" ou null
  "dateTo":    null,
  "limit":     null         // nombre de documents demandé, ou null
}

Règles:
- Mets des SYNONYMES dans docTypes: c'est ce qui rattrape un document mal titré.
- notTerms est ce qui sépare deux documents du même organisme. Utilise-le.
- N'invente pas de catégorie absente de la liste. Dans le doute, null.
- Aucun texte hors du JSON.`
